#!/usr/bin/env bash

set -v

RMS_VERSION=$(cat ./version)

RHODES_GEM=rhodes-$RMS_VERSION.gem
RHOCONNECT_GEM=rhoconnect-$RMS_VERSION.gem
RHOCONNECT_CLIENT_GEM=rhoconnect-client-$RMS_VERSION.gem
RHO_TAU_EXTENSIONS_GEM=rho-tau-extensions-$RMS_VERSION.gem

sudo apt-get -y -qq install sshpass

sshpass -p $BUILD_SERVER_PASSWORD scp $BUILD_SERVER_USER@$BUILD_SERVER_IP:/Volumes/TAU_STORAGE/BUILD_ARTEFACTS/$RMS_VERSION/$RHODES_GEM $HOME
sshpass -p $BUILD_SERVER_PASSWORD scp $BUILD_SERVER_USER@$BUILD_SERVER_IP:/Volumes/TAU_STORAGE/BUILD_ARTEFACTS/$RMS_VERSION/$RHOCONNECT_GEM $HOME
sshpass -p $BUILD_SERVER_PASSWORD scp $BUILD_SERVER_USER@$BUILD_SERVER_IP:/Volumes/TAU_STORAGE/BUILD_ARTEFACTS/$RMS_VERSION/$RHOCONNECT_CLIENT_GEM $HOME
sshpass -p $BUILD_SERVER_PASSWORD scp $BUILD_SERVER_USER@$BUILD_SERVER_IP:/Volumes/TAU_STORAGE/BUILD_ARTEFACTS/$RMS_VERSION/$RHO_TAU_EXTENSIONS_GEM $HOME
